### ISSUE TITLE
Blurry MiSTer Image After Launching Core

### ISSUE THREAD

**Issue by BradfordJoseph** [MiSTer-devel/GnW_MiSTer#16]
I installed the Game and Watch core and booted it up. Didn’t have any roms so backed out of it. Now my resolution is blurry for the entire MiSTer. Tried a reboot and change of resolutions and nothing seems to fix it. Any ideas on what I can do to fix the issue?

**Comment by pcornier** [comment]
I'm not sure whether you are referring to this core or the recently released Game and Watch core: https://github.com/agg23/fpga-gameandwatch

If it's about the new one, kindly submit the issue there. In any case, it's better to use the new core as it supports more games and has a simpler game generation system. I'm closing the issue but feel free to reopen.
