### ISSUE TITLE
Feature Request: Button that switches between Game A and Game B

### ISSUE THREAD

**Issue by KremlingKuthroat19** [MiSTer-devel/GnW_MiSTer#9]
Just a simple feature request for adding a button to switch between Game A (easy mode) and Game B (hard mode). Think of Game A and Game B like the difficulty switches on the Atari 2600.

**Comment by MilanPolle** [comment]
You can already assign the Game A and Game B buttons, to start a game with each difficulty level from the main time mode.

**Comment by KremlingKuthroat19** [comment]
Thanks! I figured it out this morning. Just operator error on my end. I'm closing the ticket.
